---
- name: debug
  hosts: webserver
  gather_facts: yes
  tasks:
    - name: print
      debug:
        msg: >
          "{{ ansible_facts['fqdn'] }} 
          {{ ansible_facts['default_ipv4']['address'] }}
          has been customized by Ansible."
