---
- name: Web application server is deployed
  hosts: webapp
  vars:
    packages:
      - nginx
      - php-fpm
      - firewalld
    web_service: nginx
    app_service: php-fpm
    firewall_service: firewalld
    firewall_service_rules:
      - http
    web_config_src: files/nginx.conf.standard
    web_config_dst: /etc/nginx/nginx.conf
    app_config_src: files/php-fpm.conf.standard
    app_config_dst: /etc/php-fpm.conf

  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present

    - name: make sure services are running
      loop: 
        - "{{ web_service }}"
        - "{{ app_service }}"
        - "{{ firewall_service }}"
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true

    - name: firewall services
      loop: "{{ firewall_service_rules }}"
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled

    - name: deploy web_config file
      notify: 
        - restart web service
      ansible.builtin.copy:
        src: "{{ web_config_src }}"
        dest: "{{ web_config_dst }}"
        mode: 0644

    - name: deploy app_config file
      notify:
        - restart app service
      ansible.builtin.copy:
        src: "{{ app_config_src }}"
        dest: "{{ app_config_dst }}"
        mode: 0644

  handlers:
    - name: restart web service
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: restarted

    - name: restart app service
      ansible.builtin.service:
        name: "{{ app_service }}"
        state: restarted

