---
- name: use student.bash_env role playbook
  hosts: devservers

  vars:
    prompt_color: blue
    default_prompt: '[\u on \h in \W dir]\$ '

  pre_tasks:
    - name: ensure test user does not exist
      ansible.builtin.user:
        name: student2
        state: absent
        force: true
        remove: true

  roles:
    - student.bash_env

  post_tasks:
    - name: create the test user
      ansible.builtin.user:
        name: student2
        state: present
        password: "{{ 'redhat' | password_hash }}"

