---
- name: Playbook Control Lab
  hosts: webservers
  vars_files: vars.yml
  tasks:
    # Fail fast message
    - name: fail if not RHEL8 and less than 256M RAM
      ansible.builtin.fail:
        msg: "minimum requirements not met"
      when: >
        ansible_facts['distribution'] != 'RedHat' or
        min_ram_mb > ansible_facts.memory_mb.real.total

    #Install all packages
    - name: ensure required packages are present
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest

    #Enable and start services 
    - name: start all services
      loop: "{{ services }}"
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true

    #Block of config tasks
    - name: setting upo the ssl cert directory and config files
      block:

        - name: create ssl cert dir
          ansible.builtin.file:
            path: "{{ ssl_cert_dir }}"
            state: directory

        - name: copy web config files
          loop: "{{ web_config_files }}"
          notify: Restart web service
          ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"

      rescue:

        - name: print failure message if either task failed
          ansible.builtin.debug:
            msg: "One or more of the configuration changes failed, but the web service is still active"

    #Configure the firewall
    - name: configure the firewall
      loop:
        - http
        - https
      ansible.posix.firewalld:
        immediate: true
        permanent: true
        state: enabled
        service: "{{ item }}" 

  #Add handlers
  handlers:

    - name: Restart web service
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: restarted
