---
- name: task failure exercise
  hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb

  tasks:

    - name: check local tim
      ansible.builtin.command: date
      register: command_result
      changed_when: false

    - name: print local time
      ansible.builtin.debug:
        var: command_result.stdout

    - name: attempt to set up a web server
      block:

       - name: install web package
         #failed_when: web_package == "httpd"
         ansible.builtin.dnf:
           name: "{{ web_package }}"
           state: present

      rescue:
       - name: install db package
         ansible.builtin.dnf:
           name: "{{ db_package }}"
           state: present

      always:
        - name: start db service
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: started

